config/routes.rb
#encoding=utf-8
Meteor::Application.routes.draw do

  root :to => 'site#index' #网站主页

  controller :home do
  	get 'admin_index' => :index #管理员主页
    get '/game_lives/delete/:id' => :delete_game  #删除主播
    get '/embarrasses/delete/:id' => :delete_embarrass #删除糗事
    get '/relax_moments/delete/:id' => :delete_relax #删除轻松一刻
    get '/topics/delete/:id' => :delete_topic #删除帖子
  end

  controller :site do

    get 'index'=> :index  #网站首页
    get 'rubyonrails' => :rubyonrails
    get '/rubyonrails/:id' => :rorshow
    get 'qingsongyike' => :qingsongyike
    get '/qingsongyike/:id' => :qsykshow
    get 'qiushibaike' => :qiushibaike
    get '/qiushibaike/:id' => :qsbkshow
    get 'youxizhibo' => :youxizhibo
    get 'wuziqi' => :wuziqi
    get '/youxizhibo/:id' => :yxzbshow
    get '/user' => :account
  end

  controller :sessions do

    get 'admin_sign_in'=> :admin_sign_in  #管理员登陆
    get '/admin_logout/:id'=> :admin_logout  #退出管理员账号
    post '/session/login'=> :admin_login  #管理员账户判断
    get '/sign_up' => :user_sign_in   #用户登录
    post '/account/user_login' => :user_login #用户账户判断
    get  '/account/user_logout/:id' => :user_logout  #用户登出
  end

  controller :admins  do

    get 'admin_sign_up'=> :sign_up   #注册管理员账户
    post '/admin/create' => :create
    get '/my_detail/:id' => :detail  #获取管理员账户信息
    get '/edit_detail/:id' => :edit
    post '/admin/update' => :update
    get '/admin/destroy/:id' => :destroy  #删除管理员账户
  end

  controller :users do

    get '/sign_in' => :user_sign_up
    post '/account/user_create' => :user_create

    post '/account/verify_password_code' => :verify_password_code
    get '/account/user_forget_password' => :forget_password
    get '/account/get_phone_code' => :get_code
    get '/account/reset_password' => :reset_password
    post '/account/password_reset' => :password_reset

    get '/my_card' => :my_info
    get 'my_info/completion' => :info_edit
    get '/constellation_date' => :constellation_date
    post '/my_info/update' => :update_info
    get  '/info_center' => :info_center

  end

  controller :user_sets do

    get '/new_topic' => :new_topic  #添加
    post '/create_topic' => :create_topic  #生成
    get '/edit_topic/:id' => :edit_topic #编辑
    post '/update_topic' => :update_user_topic #更新

    get '/new_embarrass' => :new_embarrass
    post '/create_embarrass' => :create_embarrass

    get '/new_note' => :new_note
    post '/create_note' => :create_note
    get '/edit_note/:id' => :edit_note
    post '/update_note' => :update_note

    get '/my_topic' => :my_topic
    get '/topic/delete/:id' => :delete_topic
    get '/my_embarrass' => :my_embarrass
    get '/my_note' => :my_note

  end

  resources :topics do
    post 'update_topic', :on => :collection

  end

  resources :topic_comments

  resources :embarrasses do
    collection do
      get 'applaud'
    end
  end

  resources :embarrass_comments

  resources :relax_moments do

    post 'update_relax', :on=> :collection
  end

  resources :relax_comments


  resources :game_lives do

    post 'update_live', :on=> :collection
    post 'create_cover', :on=> :collection
    get 'new_cover', :on=> :collection
  end

  resources :game_comments

end

app/views/share/_account_login.html.erb
<link href="../../../vendor/assets/stylesheets/account_login.css" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="../../../vendor/assets/javascripts/jquery.blockUI.js">
    function user_login(){
        $.blockUI({
            sition:'fixed',
            message: "<div  class='popup'>"
                    + "<div class='pop-box'>"
                    + "<div class='pop-tit'>"
                    + "<h2 class='ff-ms'>手机客户端下载</h2>"
                    + "<a class='close' href='javascript:$.unblockUI();'></a></div>"
                    + "<div class='pop-cont'>"
                    + "<div class='clearfix'>"
                    + "<h3 class='dl_h3'>下载到电脑</h3>"
                    + "<div class='dl_bar'><a class='dl_btn' href='http://www.gldjc.com/uploads/files/gcapp/release/GuangCaiClient.apk'></a><a class='dl_btn dl_btn2' href='http://itunes.apple.com/cn/app/mogujie/id700336188' target='_blank'></a></div>"
                    + "</div>"
                    + "<div class='download2 clearfix'>"
                    + "<h3 class='dl_h3'>二维码下载</h3>"
                    + "<span class='dl_ewm'></span>"
                    + "<p class='ewm_msg'>支持任何型号手机，扫码即可下载。</p>"
                    + "</div></div></div></div>",
            css: {
                left: ($(window).width() - 500) / 2 + 'px',
                top: ($(window).height() - 500) / 2 + 'px',
                border: 'none'
            }
        });
    };
</script>

app/views/share/_active_robot.html.erb
<script type="text/javascript" src="/javascripts/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="/javascripts/robot.js"></script>
<link rel="stylesheet" href="/stylesheets/robot.css" type="text/css"/>
<script type="text/javascript">
    var isindex = true;
    <% if current_user.present? %>
    var visitor = '<%= current_user.account %>';
    <% else %>
    var visitor = '<%= User.ip_to_city request.remote_ip %>';
    <% end %>

</script>
<div id="spig" class="spig" style="top: 72px; left: 1097px;">
  <div id="message">正在加载中……</div>
  <div id="mumu" class="mumu"></div>
</div>

app/views/share/_current_admin.html.erb
<% if current_admin.present? %>
    <div class="btn-group pull-right" >
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                <img src="<%= Admin::AVATAR[rand(13)] %>"style="width: 20px;height: 20px"><span class="hidden-phone"><%= current_admin.nickname %></span>
                <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
                <li><a href="/my_detail/<%= current_admin.id %>">我的信息</a></li>
                <li class="divider"></li>
                <li><a href="#">糗事百科</a></li>
                <li class="divider"></li>
                <li><a href="#">实时热闻</a></li>
                <li class="divider"></li>
                <li><a href="#">轻松一刻</a></li>
                <li class="divider"></li>
                <li><a href="#">游戏直播</a></li>
                <li class="divider"></li>
                <li><a href="/admin_logout/<%= current_admin.id %>">管理登出</a></li>
          </ul>
    </div>
<% else %>
    <div class="btn-group pull-right" >
      <a class="btn dropdown-toggle" data-toggle="dropdown">
        <i class="icon-user"></i><span class="hidden-phone">您好,新游客！</span>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><a href="#">用户注册</a></li>
        <li class="divider"></li>
        <li><a href="#">用户登录</a></li>
        <li class="divider"></li>
        <li><a href="/admin_sign_up">申请管理员资格</a></li>
        <li class="divider"></li>
        <li><a href="/admin_sign_in">我是管理我牛逼</a></li>
        <li class="divider"></li>
      </ul>
    </div>
<% end %>

app/views/share/_current_user.html.erb

    <div class="btn-group pull-right" >
      <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
        <img src="<%= @current_user.avatar || Admin::AVATAR[rand(13)] %>"style="width: 23px;height: 25px"><span class="hidden-phone"> <%= @current_user.account %></span>
        <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li><a href="/my_card">我的卡片</a></li>
        <li class="divider"></li>
        <li><a href="/my_embarrass">我的糗事</a></li>
        <li class="divider"></li>
        <li><a href="/my_topic">我的帖子</a></li>
        <li class="divider"></li>
        <li><a href="/my_note">我的记事本</a></li>
        <li class="divider"></li>
        <li><a href="/my_info/completion">完善账户信息</a></li>
        <li class="divider"></li>
        <li><a href="/account/user_logout/<%= @current_user.id %>">账号登出</a></li>
      </ul>
    </div>

app/views/share/_flash_tip.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= notice %>
    </div>
<% end %>
<% if flash[:alert] %>
    <div class="alert alert-block ">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= alert %>
    </div>
<% end %>
<% if flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= flash[:error] %>
    </div>
<% end %>
<% if flash[:success] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= flash[:success] %>
    </div>
<% end %>

app/views/share/_footer.html.erb
<footer>
  <p class="pull-left">Powered by：<a href="tencent://message/?uin=885727006&Site=gxlinzi.cn35so.cn&Menu=yes" target="_blank">暗夜ぁ大豆芽</a></p>
  <p class="pull-left">Copy by：&copy; <a  href="http://dx.pc6.com/lei/liuxing9.07.zip" target="_blank">流星蝴蝶剑</a> 2010-2014</p>
  <p class="pull-right">技术网站：
    <a href="http://api.rubyonrails.org/">Ruby官方指导</a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="https://rubygems.org/">Ruby-Gems</a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="http://ruby-china.org/lonely21475">Ruby中国社区</a>&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="http://xiemin.me/bootstrap-2.3.0/index.html">BootStrap</a>
  </p>
</footer>

app/views/share/_hot_news.html.erb
<div class="box" style="width: 300px">
  <div class="box-header well" data-original-title>
    <h2 style="font-size: 20px"><i class="icon-fire"></i>小站热榜</h2>
    <div class="box-icon">
      <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
      <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
    </div>
  </div>
  <div class="box-content">
    <ul>
      <li style="padding-left: 110px"><span class="label label-danger">热门新帖</span></li>
      <% Topic.order('created_at desc').limit(4).each do |item| %>
          <li><a href="/rubyonrails/<%= item.id %>"><%= item.topic_title[0,0] %></a></li>
      <% end %>
      <li style="text-align: center"><span class="label label-warning">搞笑趣闻</span></li>
      <% RelaxMoment.order('relax_time desc').limit(3).each do |item| %>
          <li><a href="/qingsongyike/<%= item.id %>"><%= item.relax_title[0,15] %></a></li>
      <% end %>
      <li style="text-align: center"><span class="label label-success">火热直播</span></li>
      <% GameLive.order('attention desc').limit(3).each do |item| %>
          <li><a href="/youxizhibo/<%= item.id %>"><%= item.live_title[0,15] %></a></li>
      <% end %>
      <li style="text-align: center"><span class="label label-important">捧腹糗事</span></li>
      <% Embarrass.order('chan_count desc').limit(4).each do |item| %>
          <li><a href="/qiushibaike/<%= item.id %>"><%= item.process[0,15] %></a></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/share/_javascripts.html.erb
<script src="/javascripts/jquery.js"></script>
<script src="/javascripts/jquery-1.7.2.min.js"></script>

<script src="/javascripts/bootstrap-transition.js"></script>
<!-- alert enhancer library -->
<script src="/javascripts/bootstrap-alert.js"></script>
<!-- modal / dialog library -->
<script src="/javascripts/bootstrap-modal.js"></script>
<!-- custom dropdown library -->
<script src="/javascripts/bootstrap-dropdown.js"></script>
<!-- scrolspy library -->
<script src="/javascripts/bootstrap-scrollspy.js"></script>
<!-- library for creating tabs -->
<script src="/javascripts/bootstrap-tab.js"></script>
<!-- library for advanced tooltip -->
<script src="/javascripts/bootstrap-tooltip.js"></script>
<!-- popover effect library -->
<script src="/javascripts/bootstrap-popover.js"></script>
<!-- button enhancer library -->
<script src="/javascripts/bootstrap-button.js"></script>
<!-- accordion library (optional, not used in demo) -->
<script src="/javascripts/bootstrap-collapse.js"></script>
<!-- carousel slideshow library (optional, not used in demo) -->
<script src="/javascripts/bootstrap-carousel.js"></script>
<!-- autocomplete library -->
<script src="/javascripts/bootstrap-typeahead.js"></script>
<!-- tour library -->
<script src="/javascripts/bootstrap-tour.js"></script>
<!-- library for cookie management -->
<script src="/javascripts/jquery.cookie.js"></script>
<!-- calander plugin -->
<script src='/javascripts/fullcalendar.min.js'></script>
<!-- data table plugin -->
<script src='/javascripts/jquery.dataTables.min.js'></script>

<!-- chart libraries start -->
<script src="/javascripts/excanvas.js"></script>
<script src="/javascripts/jquery.flot.min.js"></script>
<script src="/javascripts/jquery.flot.pie.min.js"></script>
<script src="/javascripts/jquery.flot.stack.js"></script>
<script src="/javascripts/jquery.flot.resize.min.js"></script>
<!-- chart libraries end -->

<!-- select or dropdown enhancer -->
<script src="/javascripts/jquery.chosen.min.js"></script>
<!-- checkbox, radio, and file input styler -->
<script src="/javascripts/jquery.uniform.min.js"></script>
<!-- plugin for gallery image view -->
<script src="/javascripts/jquery.colorbox.min.js"></script>
<!-- rich text editor library -->
<script src="/javascripts/jquery.cleditor.min.js"></script>
<!-- notification plugin -->
<script src="/javascripts/jquery.noty.js"></script>
<!-- file manager library -->
<script src="/javascripts/jquery.elfinder.min.js"></script>
<!-- star rating plugin -->
<script src="/javascripts/jquery.raty.min.js"></script>
<!-- for iOS style toggle switch -->
<script src="/javascripts/jquery.iphone.toggle.js"></script>
<!-- autogrowing textarea plugin -->
<script src="/javascripts/jquery.autogrow-textarea.js"></script>
<!-- multiple file upload plugin -->
<script src="/javascripts/jquery.uploadify-3.1.min.js"></script>
<!-- history.js for cross-browser state change on ajax -->
<script src="/javascripts/jquery.history.js"></script>
<script src="/javascripts/jquery-ui-1.8.21.custom.min.js"></script>
<!-- application script for Charisma demo -->
<script src="/javascripts/charisma.js"></script>
<!-- 副文本编辑器js -->
<script src="/javascripts/bootstrap-wysiwyg.js"></script>
<script src="/javascripts/text-scroll.multi.js"></script>
<script src="/javascripts/jquery.hotkeys.js"></script>
<!--页面遮罩层-->
<script src="/javascripts/jquery.blockUI.js"></script>

app/views/share/_push_ad.html.erb
<div class="box">
  <div class="box-header well" data-original-title>
    <h3><i class="icon-fire"></i>推广链接</h3>
    <div class="box-icon">
      <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
      <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>
    </div>
  </div>
  <div class="box-content" style="background-color: white">
    <span>
      <img src="/img/lol/blade.gif" style="max-width: 260px">
    </span>
  </div>
</div>

app/views/share/_right_menu.html.erb
<div class="well nav-collapse sidebar-nav"><!-- 左侧菜单 -->
  <ul class="nav nav-tabs nav-stacked main-menu">
    <li class="nav-header hidden-tablet">管理模块</li>
    <li><a class="ajax-link" href="/admin_index"><i class="icon-home"></i><span class="hidden-tablet">网站数据</span></a></li>
    <li><a class="ajax-link" href="#"><i class=" icon-user"></i><span class="hidden-tablet">成员列表</span></a></li>
    <li class="nav-header hidden-tablet">偏好设置</li>
    <li><a class="ajax-link" href="<%= topics_path %>"><i class="icon-th-list"></i><span class="hidden-tablet"> 技术文章</span></a></li>
    <li><a class="ajax-link" href="<%= embarrasses_path %>"><i class="icon-film"></i><span class="hidden-tablet"> 糗事百科</span></a></li>
    <li><a class="ajax-link" href="<%= relax_moments_path %>"><i class="icon-edit"></i><span class="hidden-tablet"> 轻松一刻</span></a></li>
    <li><a class="ajax-link" href="<%= game_lives_path %>"><i class="icon-refresh"></i><span class="hidden-tablet"> 游戏直播</span></a></li>
  </ul>
  <label id="for-is-ajax" class="hidden-tablet" for="is-ajax"><input id="is-ajax" type="checkbox">动态菜单</label>
</div>

app/views/share/_site_carousel.html.erb
<div id="myCarousel" class="carousel slide">
  <div class="carousel-inner">

    <div class="item active">
      <% live_carousel =GameLive.order('attention desc').limit(1).first%>
      <img src="/images/carousel/lol<%= rand(4)%>.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>英雄联盟</h1>
          <p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;在这里，魔法不只是一种神秘莫测的能量概念。它是实体化的物质，可以被引导、成形、塑造和操作。符文之地的魔法拥有自己的自然法则。源生态魔法随机变化的结果改变了科学法则。</p>
          <a class="btn btn-large" href="/youxizhibo">激情直播</a>
        </div>
      </div>
    </div>

    <div class="item">
      <img src="/images/carousel/ruby<%= rand(3)%>.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>Ruby on Rails</h1>
          <p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ruby on Rails，简称Rails，是一个使用Ruby语言写的开源Web应用框架，它是严格按照MVC结构开发的。它努力使自身保持简单，来使实际的应用开发时的代码更少，使用最少的配置。Rails的设计原则包括“不做重复的事”（Don't Repeat Yourself）和“惯例优于设置”（Convention Over Configuration）</p>
          <a class="btn btn-large btn-success" href="/rubyonrails">获益匪浅</a>
        </div>
      </div>
    </div>

    <div class="item">
      <img src="/images/carousel/qingsong<%= rand(3)%>.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>轻松一刻</h1>
          <p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;轻松一刻这个栏目是网易的，是小编的，更是广大易友和我们一起创造的奇迹。1年里我们一起经历了春夏秋天，无论风雨，无论节假日，我们都会在固定的老地方等你们，虽然我们孱弱过，也会姗姗来迟八点二十发过，不过我们从不会爽约。1周年是一个新的起点，请和我一起，爱生活，爱轻松一刻。</p>
          <a class="btn btn-large btn-info" href="/qingsongyike">神采飞扬</a>
        </div>
      </div>
    </div>

    <div class="item">
      <img src="/images/carousel/qiushi<%= rand(3)%>.jpg" alt="">
      <div class="container">
        <div class="carousel-caption">
          <h1>糗事百科</h1>
          <p class="lead">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;是以糗友真实糗事为主题的笑话网站，话题轻松休闲，在年轻人中十分流行。在糗事百科中可以查看他人发布的糗事并与网友分享自己亲身经历或听说到的油菜、杯具、草蛋、有意思的、不顺心的等各类情形的生活糗事，并且可以左右排名。但是最近糗事百科的糗事有涉黄的嫌疑，偏离了一开始的方向。</p>
          <a class="btn btn-large btn-primary" href="qiushibaike">莞尔一笑</a>
        </div>
      </div>
    </div>
  </div>

  <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>
<script src="bootstrap-carousel.js">
    !function ($) {
        $(function(){
            $('#myCarousel').carousel()
        })
    }(window.jQuery)
</script>

app/views/share/_site_header.html.erb
<!-- 导航栏-->
<div class="navbar-wrapper" style="position: fixed">
  <div class="container">
    <div class="navbar navbar-inverse">
      <div class="navbar-inner" style="filter:alpha(Opacity=60);-moz-opacity:0.6;opacity:0.6">
        <a class="brand" href="/" style="color: #FDF216"><img src="/img/lol/douya.png" width="30px" height="30px">&nbsp;丶大豆芽</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li><a href="/rubyonrails">Ruby<i class="icon-bookmark"></i>Rails</a></li>
            <li><a href="/qiushibaike">糗事<i class="icon-heart"></i>百科</a></li>
            <li><a href="/qingsongyike">轻松<i class="icon-green icon-music"></i>一刻</a></li>
            <li><a href="/youxizhibo">游戏<i class="icon-facetime-video"></i>直播</a></li>
            <li class="dropdown">
              <%= render :partial=>'share/current_account' %>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/share/_stylesheets.html.erb
<link type="text/css" href="/stylesheets/bootstrap-cerulean.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/bootstrap-responsive.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/charisma-app.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/chat-bubble.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/chosen.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/colorbox.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/elfinder.min.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/elfinder.theme.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/fullcalendar.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/fullcalendar.print.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/jquery-ui-1.8.21.custom.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/jquery.iphone.toggle.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/jquery.cleditor.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/jquery.noty.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/noty_theme_default.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/opa-icons.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/uploadify.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/uniform.default.css" media="all" rel="stylesheet">
<link type="text/css" href="/stylesheets/will_paginate.css" media="all" rel="stylesheet">

app/views/share/_user_right_menu.html.erb
<div class="well nav-collapse sidebar-nav"><!-- 左侧菜单 -->
  <ul class="nav nav-tabs nav-stacked main-menu">
    <li class="nav-header hidden-tablet">个人中心</li>
    <li><a class="ajax-link" href="/info_center"><i class="icon-home"></i><span class="hidden-tablet"> 信息中心</span></a></li>
    <li><a class="ajax-link" href="/my_card" target="_blank"><i class="icon-user"></i><span class="hidden-tablet"> 我的名片</span></a></li>
    <li><a class="ajax-link" href="/my_info/completion" target="_blank"><i class="icon-edit"></i><span class="hidden-tablet"> 完善信息</span></a></li>
    <li><a class="ajax-link" href="#"><span class="hidden-tablet">
          <object type="application/x-shockwave-flash" data="/player/dewplayer.swf" width="100%" height="20" id="dewplayer" name="dewplayer">
            <param name="wmode" value="transparent" />
            <param name="movie" value="/player/dewplayer.swf" />
            <param name="flashvars" value="mp3=/music/Catch My Breath.mp3&amp;autostart=0&amp;showtime=1&amp;nopointer=1&amp;volume=80" />
          </object>
      </span></a>
    </li>
    <li class="nav-header hidden-tablet">偏好设置</li>
    <li><a class="ajax-link" href="/new_topic"><i class="icon-book"></i><span class="hidden-tablet"> 发布新帖</span></a></li>
    <li><a class="ajax-link" href="/new_embarrass"><i class="icon-thumbs-up"></i><span class="hidden-tablet"> 糗事投稿</span></a></li>
    <li><a class="ajax-link" href="/new_note"><i class="icon-pencil"></i><span class="hidden-tablet"> 随时笔记</span></a></li>
    <li><a class="ajax-link" href="/wuziqi"><i class="icon-fire"></i><span class="hidden-tablet"> 休闲娱乐</span></a></li>
  </ul>
</div>