config/routes.rb
#encoding=utf-8
Meteor::Application.routes.draw do

  root :to => 'site#index' #网站主页

  controller :home do
  	get 'admin_index' => :index #管理员主页
    get '/game_lives/delete/:id' => :delete_game  #删除主播
    get '/embarrasses/delete/:id' => :delete_embarrass #删除糗事
    get '/relax_moments/delete/:id' => :delete_relax #删除轻松一刻
    get '/topics/delete/:id' => :delete_topic #删除帖子
  end

  controller :site do

    get 'index'=> :index  #网站首页
    get 'rubyonrails' => :rubyonrails
    get '/rubyonrails/:id' => :rorshow
    get 'qingsongyike' => :qingsongyike
    get '/qingsongyike/:id' => :qsykshow
    get 'qiushibaike' => :qiushibaike
    get '/qiushibaike/:id' => :qsbkshow
    get 'youxizhibo' => :youxizhibo
    get 'wuziqi' => :wuziqi
    get '/youxizhibo/:id' => :yxzbshow
    get '/user' => :account
  end

  controller :sessions do

    get 'admin_sign_in'=> :admin_sign_in  #管理员登陆
    get '/admin_logout/:id'=> :admin_logout  #退出管理员账号
    post '/session/login'=> :admin_login  #管理员账户判断
    get '/sign_up' => :user_sign_in   #用户登录
    post '/account/user_login' => :user_login #用户账户判断
    get  '/account/user_logout/:id' => :user_logout  #用户登出
  end

  controller :admins  do

    get 'admin_sign_up'=> :sign_up   #注册管理员账户
    post '/admin/create' => :create
    get '/my_detail/:id' => :detail  #获取管理员账户信息
    get '/edit_detail/:id' => :edit
    post '/admin/update' => :update
    get '/admin/destroy/:id' => :destroy  #删除管理员账户
  end

  controller :users do

    get '/sign_in' => :user_sign_up
    post '/account/user_create' => :user_create

    post '/account/verify_password_code' => :verify_password_code
    get '/account/user_forget_password' => :forget_password
    get '/account/get_phone_code' => :get_code
    get '/account/reset_password' => :reset_password
    post '/account/password_reset' => :password_reset

    get '/my_card' => :my_info
    get 'my_info/completion' => :info_edit
    get '/constellation_date' => :constellation_date
    post '/my_info/update' => :update_info
    get  '/info_center' => :info_center

  end

  controller :user_sets do

    get '/new_topic' => :new_topic  #添加
    post '/create_topic' => :create_topic  #生成
    get '/edit_topic/:id' => :edit_topic #编辑
    post '/update_topic' => :update_user_topic #更新

    get '/new_embarrass' => :new_embarrass
    post '/create_embarrass' => :create_embarrass

    get '/new_note' => :new_note
    post '/create_note' => :create_note
    get '/edit_note/:id' => :edit_note
    post '/update_note' => :update_note

    get '/my_topic' => :my_topic
    get '/topic/delete/:id' => :delete_topic
    get '/my_embarrass' => :my_embarrass
    get '/my_note' => :my_note

  end

  resources :topics do
    post 'update_topic', :on => :collection

  end

  resources :topic_comments

  resources :embarrasses do
    collection do
      get 'applaud'
    end
  end

  resources :embarrass_comments

  resources :relax_moments do

    post 'update_relax', :on=> :collection
  end

  resources :relax_comments


  resources :game_lives do

    post 'update_live', :on=> :collection
    post 'create_cover', :on=> :collection
    get 'new_cover', :on=> :collection
  end

  resources :game_comments

end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :account %><br />
    <%= f.text_field :account %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :login_ip %><br />
    <%= f.text_field :login_ip %>
  </div>
  <div class="field">
    <%= f.label :login_count %><br />
    <%= f.number_field :login_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Account:</b>
  <%= @admin.account %>
</p>

<p>
  <b>Password:</b>
  <%= @admin.password %>
</p>

<p>
  <b>Email:</b>
  <%= @admin.email %>
</p>

<p>
  <b>Phone:</b>
  <%= @admin.phone %>
</p>

<p>
  <b>Login ip:</b>
  <%= @admin.login_ip %>
</p>

<p>
  <b>Login count:</b>
  <%= @admin.login_count %>
</p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/admins/sign_up.html.erb
<div class="container-fluid" style="padding-top: 100px">
  <div class="row-fluid">
    <div class="row-fluid">
      <div class="span9 center login-header">
        <div class="alert alert-success">
          <h2>大豆芽 ❤ 申请新管理员账号 </h2>
        </div>
      </div>
    </div>

    <div class="row-fluid">
      <div class="well span5 center login-box">
        <% if flash[:notice] %>
            <div class="alert alert-info">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= notice %>
            </div>
        <% end %>
        <% if flash[:alert] %>
            <div class="alert alert-block ">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= alert %>
            </div>
        <% end %>
        <% if flash[:error] %>
            <div class="alert alert-error">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= flash[:error] %>
            </div>
        <% end %>
        <% if flash[:success] %>
            <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">×</button>
              <%= flash[:success] %>
            </div>
        <% end %>
        <!-- devise的提示信息 end -->
        <form accept-charset="utf-8" action="/admin/create" method="post">
          <div class="input-prepend" title="请输入邀请码" data-rel="tooltip">
            <span class="add-on"><i class="icon-qrcode"></i></span>
            <input type="text" name="invitation" value="<%= params[:code] %>" class="input-large span6" placeholder="没有邀请码是不会注册成功的！">
          </div>
          <div class="clearfix"></div>

          <div class="input-prepend" title="请输入昵称" data-rel="tooltip">
            <span class="add-on"><i class="icon-comment"></i></span>
            <input type="text" name="nickname" value="<%= params[:name] %>" class="input-large span6" placeholder="一个好的昵称有助于你装逼">
          </div>
          <div class="clearfix"></div>

          <div class="input-prepend" title="请输入您的登陆账号" data-rel="tooltip" data-placement="top">
            <span class="add-on"><i class="icon-user"></i></span>
            <input type="text" name="account" value="<%= params[:account] %>" class="input-large span6" placeholder="手机/邮箱/QQ号">
          </div>
          <div class="clearfix"></div>

          <div class="input-prepend" title="请输入您的登陆密码" data-rel="tooltip">
            <span class="add-on"><i class="icon-lock"></i></span>
            <input type="password" name="password" class="input-large span6" placeholder="听说密码越长越牛逼">
          </div>
          <div class="clearfix"></div>

          <div class="input-prepend">
            <label class="remember" for="remember"  title="记住我" data-rel="tooltip"><input type="checkbox" id="remember">记住账号</label>
          </div>
          <div class="clearfix"></div>

          <p class="center span4">
            <button type="submit" class="btn btn-large btn-danger">强势注册</button>
          </p>
          <div class="clearfix"></div>

        </form>
      </div>
    </div>

  </div>
</div>